### ISSUE TITLE
Albums created in Immich but no pictures transfered

### ISSUE THREAD

**Issue by electronick86** [giuliolibrando/photoprism2immich#1]
Hello.

I would like to migrate to Immich and find this script that looks perfect for the migration.

I'm able to run it and it create the albums in Immich but images are not transfered. Base on this output, could you help me to find the issue?

```
Migrating album: ALL
Migrating album '10 ans Simon Arboreo' (UID: asdssq8373ragja3)
No match: 2024/05/20240518_132310_7044F4CB.jpg in Immich
No match: 2024/05/20240518_132227_8E7D8BB8.jpg in Immich
[...]
No match: 2024/05/20240518_101855_175742E2.jpg in Immich
Images found in Immich: 0
Images not found in Immich:
 - 2024/05/20240518_132310_7044F4CB.jpg
 - 2024/05/20240518_132227_8E7D8BB8.jpg
[...]
 - 2024/05/20240518_101855_175742E2.jpg
Migration complete.
```

**Comment by giuliolibrando** [comment]
Have you changed the Immich default library path from /YYYY/MM/DD to /YYYY/MM before using the script to migrate photos and albums?

**Comment by electronick86** [comment]
Hello @giuliolibrando 

Thanks for your reply. I didn't changed thant indeed.

Is it under "storage template"? Should I configure it like that? Storage template was disabled. I changed it like on this printscreen, remove a album line from `migrated_albums.log` and reexecute the script but the output is the same.

<img width="459" alt="System_Settings_-_Immich_et_Toutes_les_boîtes" src="https://github.com/user-attachments/assets/b5f956f1-b682-4bdb-88af-c1e25a30c23a">

**Comment by giuliolibrando** [comment]
You need to re-import eveyr image before migrating albums. The album migration function is just a double check source/pathfile dest/pathfile. If there's a match it will link it inside the album via api but the file must be already there on immich

**Comment by electronick86** [comment]
Thanks!

I just had to add two imports here (https://github.com/giuliolibrando/photoprism2immich/blob/80ef9df4dd32dd5aad29aa9b0295e28485837163/photoprism2immich/photoprism2immich.py#L6) 

```
from datetime import datetime
import requests
```

and now the import-library script is running. After that I'll be able to assign the pictures in their respective albums. Thanks for sharing this migration script!
