### ISSUE TITLE
Missing imports (requests/datetime) and click in requirements.txt

### ISSUE THREAD

**Issue by mycarrysun** [giuliolibrando/photoprism2immich#2]
From a fresh install there are a few packages that are not imported that should be:
- datetime
- requests

I also had to manually install `click` - I don't see it in `requirements.txt`.

After this the script worked.

**Comment by giuliolibrando** [comment]
Thanks for the feedback. datetime and requests are already imported in immich_api.py, what are you referring to? I'm adding `click` to the requirements as probably was already installed on my setup and I didn't noticed it, thanks.

**Comment by mycarrysun** [comment]
https://github.com/giuliolibrando/photoprism2immich/blob/main/photoprism2immich/photoprism2immich.py#L30
and
https://github.com/giuliolibrando/photoprism2immich/blob/main/photoprism2immich/photoprism2immich.py#L20

**Comment by giuliolibrando** [comment]
Files updated with changes
