### ISSUE TITLE
Skips multiple real media types: gif, mp, webp

### ISSUE THREAD

**Issue by mycarrysun** [giuliolibrando/photoprism2immich#3]
There are possibly more, but the skipping behavior is not great...need more file extensions and it might be just better to try and submit it to the api anyways and let immich tell you if its supported

**Comment by giuliolibrando** [comment]
I built the script using this table as reference https://immich.app/docs/features/supported-formats/ . It has been updated in those months so more filetypes are supported now. I'll update the supperted filetype in the script. I know there could be better ways (like parsing the return message from immich despite selecting it in advance) but.. it just works. If you wrote a better function and want to share it here you're welcome

**Comment by mycarrysun** [comment]
I don't mean parsing the return message to see if its supported - I just mean sending it the file and let it throw an error but continue running the script.

**Comment by giuliolibrando** [comment]
I've added the requested file formats in the code, plus added every currently supported format by Immich. I'm not going to edit the function as I current have no test environment and I don't want to mess with my production immich instance. Anybody feel free to add a PR to update that part
