### ISSUE TITLE
AttributeError: module 'datetime' has no attribute 'fromtimestamp'

### ISSUE THREAD

**Issue by haris2887** [giuliolibrando/photoprism2immich#4]
When Running the import all.
I am getting 
AttributeError: module 'datetime' has no attribute 'fromtimestamp'

`Scanning directory: /Orignals
Uploading file: /Orignals/2013/08/20130809_122538_CEA4BDD4.jpg
Traceback (most recent call last):
  File "/usr/local/bin/photoprism2immich", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/photoprism2immich/photoprism2immich.py", line 113, in main
    upload_files_from_path(args.originals, args.apikey, args.baseapiurl, args.log)
  File "/usr/local/lib/python3.9/site-packages/photoprism2immich/photoprism2immich.py", line 73, in upload_files_from_path
    upload(file_path, api_key, base_url, log_file)
  File "/usr/local/lib/python3.9/site-packages/photoprism2immich/photoprism2immich.py", line 22, in upload
    'fileCreatedAt': datetime.fromtimestamp(stats.st_mtime),
AttributeError: module 'datetime' has no attribute 'fromtimestamp'`

**Comment by Tueska** [comment]
I just had the same error and fixed it locally on my machine, now the Script works fantastically and is currently uploading to my new immich Instance :)
You can fix it yourself too rather easily and quick until we get a proper patch:

1. Open the file that's mentioned in your log: /usr/local/lib/python3.9/site-packages/photoprism2immich/photoprism2immich.py
2. Replace the import in Line 5 from `import datetime` to `from datetime import datetime`

OR you can change the two lines (22 and 23) that call `datetime.fromtimestamp` to `datetime.datetime.fromtimestamp`

**Comment by au12** [comment]
Just ran into this problem. Changing "import datetime" to "from datetime import datetime" worked! Thank you!!

**Comment by giuliolibrando** [comment]
Thanks @Tueska. I updated the code
